# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='sex_field',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('Pref', 'Prefer Not to Respond')], default='---', max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='shirt_size_field',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L')], default='Small', max_length=200),
        ),
        migrations.AddField(
            model_name='person',
            name='skill_field',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='buy_options_field',
            field=models.CharField(choices=[('Shirt', 'shirt'), ('Frisbee', 'frisbee')], default='None', max_length=200),
        ),
    ]
