# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 18:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20160608_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='choices',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
