# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20160608_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='the_choices',
            field=models.ManyToManyField(to='register.Choices'),
        ),
    ]
