# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20160609_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShirtOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='buy_options',
            field=models.ManyToManyField(to='register.ShirtOptions'),
        ),
    ]
