# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_auto_20160609_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirtoptions',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
