# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_auto_20160609_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=localflavor.us.models.PhoneNumberField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='skill',
            field=models.CharField(choices=[(b'1', 1), (b'2', 2), (b'3', 3), (b'4', 4), (b'5', 5)], default=1, max_length=200),
        ),
    ]
